// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN-IZhELt_9j1g-IiLkR9jcd4WaxuTuz0',
    appId: '1:752134733208:web:c6bc3d33e169b35f7affed',
    messagingSenderId: '752134733208',
    projectId: 'safeher-ccfe5',
    authDomain: 'safeher-ccfe5.firebaseapp.com',
    storageBucket: 'safeher-ccfe5.firebasestorage.app',
    measurementId: 'G-YMJ7MC5CL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaNmRskprUhYZp66KKLZsZjv__AmUnI9I',
    appId: '1:752134733208:android:ca9bedea1d3012087affed',
    messagingSenderId: '752134733208',
    projectId: 'safeher-ccfe5',
    storageBucket: 'safeher-ccfe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNJ2r8ficUCq3IAQWs3GwoWNO7P-yuevo',
    appId: '1:752134733208:ios:ce9fad5aa4db52377affed',
    messagingSenderId: '752134733208',
    projectId: 'safeher-ccfe5',
    storageBucket: 'safeher-ccfe5.firebasestorage.app',
    iosBundleId: 'com.example.safeher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNJ2r8ficUCq3IAQWs3GwoWNO7P-yuevo',
    appId: '1:752134733208:ios:ce9fad5aa4db52377affed',
    messagingSenderId: '752134733208',
    projectId: 'safeher-ccfe5',
    storageBucket: 'safeher-ccfe5.firebasestorage.app',
    iosBundleId: 'com.example.safeher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN-IZhELt_9j1g-IiLkR9jcd4WaxuTuz0',
    appId: '1:752134733208:web:1d335b4294e7e64e7affed',
    messagingSenderId: '752134733208',
    projectId: 'safeher-ccfe5',
    authDomain: 'safeher-ccfe5.firebaseapp.com',
    storageBucket: 'safeher-ccfe5.firebasestorage.app',
    measurementId: 'G-WVL3Q5QB6J',
  );

}